name: GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install nim
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
        sh init.sh -y
        choosenim update stable

    - name: Build
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nimble docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs
